### ISSUE TITLE
Updating private go modules does not work in golang-devtools

### ISSUE THREAD

**Issue by nhhagen** [coopnorge/engineering-docker-images#1221]
When trying to update a private dependency in helloworld `go get -u` fails

```console
❯ docker compose run --rm golang-devtools go get -u github.com/coopnorge/go-services-interfaces
[+] Creating 3/0
 ✔ Network helloworld_default          Created                                                                                                          0.0s
 ✔ Volume "helloworld_nothing"         Created                                                                                                          0.0s
 ✔ Volume "helloworld_xdg-cache-home"  Created                                                                                                          0.0s
go: downloading github.com/coopnorge/go-services-interfaces v0.0.0-20230907095023-f2b3962c1e12
go: github.com/coopnorge/go-services-interfaces@v0.0.0-20230907095023-f2b3962c1e12: verifying module: github.com/coopnorge/go-services-interfaces@v0.0.0-20230907095023-f2b3962c1e12: reading https://sum.golang.org/lookup/github.com/coopnorge/go-services-interfaces@v0.0.0-20230907095023-f2b3962c1e12: 404 Not Found
        server response:
        not found: github.com/coopnorge/go-services-interfaces@v0.0.0-20230907095023-f2b3962c1e12: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/112b42974f1fcf24cffb55d89f99ad5218e8cefe73eed136add6a68288159b25: exit status 128:
                fatal: could not read Username for 'https://github.com': terminal prompts disabled
        Confirm the import path was entered correctly.
        If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
```

After some research I found that `GOPRIVATE` is empty in `golang-devtools`.

```console
❯ docker compose run --rm golang-devtools go env GOPRIVATE

```

When adding `RUN  go env -w GOPRIVATE=github.com/coopnorge/*` to the `golang-devtools` definition in `docker-compose/Dockerfile` I am able to update the package.

```Dockerfile
FROM ghcr.io/coopnorge/engineering-docker-images/e0/devtools-golang-v1beta1:gitc-1f40b7aec2da97d51ed26c6f1d027bdee0458a0d@sha256:5abec21bdbd1fec9946a50e825692773a64e7db2ddd10d3446e1fc70cfcbca3b AS golang-devtools
RUN  go env -w GOPRIVATE=github.com/coopnorge/*
```

```console
❯ docker compose run --rm golang-devtools go env GOPRIVATE
github.com/coopnorge/*
```

```console
❯ docker compose run --rm golang-devtools go get -u github.com/coopnorge/go-services-interfaces
go: upgraded github.com/coopnorge/go-services-interfaces v0.0.0-20221118083324-66939a199938 => v0.0.0-20230907095023-f2b3962c1e12
...
...
```

This is a functional workaround, but it also requires every repository to be configured correctly.

I suggest we find a way add the required configuration to the image. One solution is to add `RUN  go env -w GOPRIVATE=github.com/coopnorge/*` command to `images/devtools-golang-v1beta1/context/Dockerfile`.

This also adds the question if we should add the git configuration for private go modules to `images/devtools-golang-v1beta1/context/Dockerfile`. Today we require each engineer to [configure this](https://inventory.internal.coop/docs/default/system/engineering-docker-images/images/devtools-golang-v1beta1/#local-go-configuration) as a part of their setup.

```
RUN git config --global url."git@github.com:coopnorge/".insteadOf "https://github.com/coopnorge/"
```

**Comment by AtzeDeVries** [comment]
what about using the go env config file.

this is set by the `GOENV` setting. 

```
go env | grep ENV
GOENV="/Users/atze/Library/Application Support/go/env"
```

this contains 
```
cat "/Users/atze/Library/Application Support/go/env"
GOPATH=/Users/atze/go
GOPRIVATE=github.com/coopnorge
```

So instead of setting the go private in the image we set
```
FROM ghcr.io/coopnorge/engineering-docker-images/e0/devtools-golang-v1beta1:gitc-1f40b7aec2da97d51ed26c6f1d027bdee0458a0d@sha256:5abec21bdbd1fec9946a50e825692773a64e7db2ddd10d3446e1fc70cfcbca3b AS golang-devtools
RUN  go env -w GOENV=/goenv
```
Then mount either your local env file, or a repository managed env file in the container using the docker compose config

**Comment by nhhagen** [comment]
I thought of that, but we then have to update every Golang repository to mount your local go env configuration.

Who are we building these images for?
- any engineer
- engineers working at Coop Norge

If the case is "any engineer" we cannot have any Coop Norge specific things in the image, but if we are building this for "engineers working at Coop Norge" we should consider bundling "static configuration" like the location of private dependencies.

When it comes to credentials we have to inject that, for security reasons we can not bundle that with the image.

**Comment by nhhagen** [comment]
We can also see CI failing after updating an image here: https://github.com/coopnorge/helloworld/actions/runs/6119004109/job/16608086998?pr=394

**Comment by AtzeDeVries** [comment]
yeah fair point, the only think i was looking into is making the config exposable and not part of a dockerfile. I think it is correct to not mount your local go env, so either we could go for a good default, and be able to override this per repo or per person with a mount of this go env file. This to me is a slightly better approach setting the config in the dockerfile.

**Comment by nhhagen** [comment]
Ooops, I managed to delete the wrong comment
