### ISSUE TITLE
fix distrubution of images over gh actions

### ISSUE THREAD

**Issue by AtzeDeVries** [coopnorge/engineering-docker-images#34]
Currently it look like we for each image repo (terraform/golang etc) need to give access to repo's which one to use it. I have not found a way to wildcard this.

**Comment by nhhagen** [comment]
@AtzeDeVries we could also consider do make all the images public in this case as the repository is public.

**Comment by AtzeDeVries** [comment]
Dont see why not

**Comment by nhhagen** [comment]
lets to it

**Comment by nhhagen** [comment]
we have to enable support at the org level

**Comment by nhhagen** [comment]
The images in this repo are now public
