### ISSUE TITLE
techdocs image - cannot start mkdocs server

### ISSUE THREAD

**Issue by ianrobrien** [coopnorge/engineering-docker-images#465]
Running the command:

> docker run -v $(pwd):/content -p 3000:3000 ghcr.io/coopnorge/engineering-docker-images/e0/techdocs techdocs-cli serve --no-docker -v

results in the following error:

> info: Starting mkdocs server.
verbose: [mkdocs] Error: Config file 'mkdocs.yml' does not exist.
info: Waiting for mkdocs server to start...
error: mkdocs server did not start. Exiting. Try re-running command with -v option for more details.
Non zero exit code from child process

**Comment by aucampia** [comment]
@ianrobrien 

you need to do this:

```
$ docker-compose run --rm techdocs bash -c 'export SITE_NAME="Coop Playbook" && export REPO_NAME= export REPO_URL= && export EDIT_URL= && techdocs-cli serve:mkdocs --no-docker'
Creating coop-playbook_techdocs_run ... done

info: 
Starting mkdocs server on http://127.0.0.1:8000
```

If we add a makefile target it will be easier, but the problem is that it needs to listen on 0.0.0.0 because otherwise you can't get to it from outside the container.
