### ISSUE TITLE
Fix failing build in PR for golangci lint

### ISSUE THREAD

**Issue by ianrobrien** [coopnorge/engineering-docker-images#492]
The CI is failing for bumping golangci/golangci-lint from v1.48.0-alpine to v1.50.1-alpine in /images/devtools-golang-v1beta1/context

I believe this is due to new linting rules.

Ref:
- https://github.com/coopnorge/engineering-docker-images/pull/421
- https://github.com/coopnorge/engineering-docker-images/actions/runs/3442814733/jobs/5743744681

**Comment by nhhagen** [comment]
Dependabot has closed the failing PR as golangci-lint was up to date at the time of closing the PR.
