### ISSUE TITLE
Fix failing build in PR for bumping node in techdocs

### ISSUE THREAD

**Issue by ianrobrien** [coopnorge/engineering-docker-images#517]
Build is failing for bumping library/node from 18.10.0-bullseye to 19.1.0-bullseye in /images/techdocs/context

> ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref nkhbkl5rncnjgo0weainvotyd::ga2degctfbtxe0vpo6uyss9ri: failed to walk /tmp/buildkit-mount2019063959/usr/local/share/systemtap/tapset: lstat /tmp/buildkit-mount2019063959/usr/local/share/systemtap/tapset: no such file or directory

https://github.com/coopnorge/engineering-docker-images/actions/runs/3471310263/jobs/5800640310

**Comment by nhhagen** [comment]
node has been bumped, no need to fix
