### ISSUE TITLE
(techdocs): Missing .vale.ini

### ISSUE THREAD

**Issue by misund** [coopnorge/engineering-docker-images#526]
It looks like vale does not find a config file whenever it runs.

Propose to fix by looking for the file in the source repo. Maybe also fall back to a default config file.

**Comment by nhhagen** [comment]
@misund currently we require every repo to provide its own `.vale.ini` file.

@coopnorge/engineering do we want the image to fall back to a default `.vale.ini`?

**Comment by nhhagen** [comment]
We will continue to require a `.vale.ini` file in repos using this image.
