### ISSUE TITLE
mkdocs devtools image

### ISSUE THREAD

**Issue by aucampia** [coopnorge/engineering-docker-images#69]
Create a devtools image for mkdocs - this will basically do the same as the devtools for coop-playbook.

**Comment by aucampia** [comment]
Work started here: https://github.com/coopnorge/engineering-docker-images/tree/iwana-20220428T0859-mkdocs

**Comment by nhhagen** [comment]
With Inventory we now use TechDocs to publish documentation inside of Inventory. [Backstage TechDocs Engineering Image](https://github.com/coopnorge/engineering-docker-images/tree/main/images/techdocs) that covers the required tool chain and [TechDocs GitHub Actions Workflow](https://inventory.internal.coop/docs/default/component/github-workflow-techdocs) that covers CI and deployment of the documentation.
