### ISSUE TITLE
Running terraform as amd64 on arm causes issues with validation

### ISSUE THREAD

**Issue by AtzeDeVries** [coopnorge/engineering-docker-images#70]
OS: Mac OS with ARM

If you run a local terraform init with terraform ARM based version the docker image will fail on the providers since they are architecture specific.  Would be nice if we build ARM images, then the problem would go away.

Other solution would be to advice to always terraform AMD64 (although this does not work with tfswitch)

**Comment by AtzeDeVries** [comment]
providers are also downloaded with arm modules now so this should not be a problem.

**Comment by kvendingoldo** [comment]
btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.
