### ISSUE TITLE
terraform devtools image: generate SARIF output for tools that support it, like tfsec

### ISSUE THREAD

**Issue by aucampia** [coopnorge/engineering-docker-images#76]
This is so we can upload it to github.

https://github.com/microsoft/sarif-tutorials/blob/main/docs/1-Introduction.md

**Comment by nhhagen** [comment]
Here is the option for outputing a sarif file from tfsec. https://github.com/aquasecurity/tfsec-sarif-action/blob/9b703869c5108700605056134506e274ef6e9bd3/entrypoint.sh#L43

**Comment by AtzeDeVries** [comment]
we already do sarif through the security scanning pipeline so i dont think we need to implement it here.
