### ISSUE TITLE
Use GitHub API to fetch the latest version of tfswitch instead of hardcode the in version in code 

### ISSUE THREAD

**Issue by nikitabarskov** [coopnorge/engineering-docker-images#84]
https://github.com/coopnorge/engineering-docker-images/blob/e217075a99480c4ccc326705e50f25452b6574f0/images/devtools-terraform-v1beta1/context/Dockerfile#L44

GitHub API has [Releases API]. So, we can fetch [the latest release], filter the response by architectures and OSs we need, and then use `.browser_download_url` to download the artifact.

For example, look at this straightforward solution:

```Dockerfile
RUN curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/warrensbox/terraform-switcher/releases/latest" | jq -r ".name" > .terraform-switcher-version && \
    curl -LOJ "https://github.com/warrensbox/releases/$(cat .terraform-switcher-version)/terraform-switcher_$(cat .terraform-switcher-version)_linux_amd64.tar.gz" && \
    curl -LOJ "https://github.com/warrensbox/releases/$(cat .terraform-switcher-version)/terraform-switcher_$(cat .terraform-switcher-version)_checksums.txt" && \
    sha256sum -c "terraform-switcher_$(cat .terraform-switcher-version)_checksums.txt"
```

Tho, it can be a problem with local development, because GitHub API has 60 requests per hour limitation: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

[Releases API]: https://docs.github.com/en/rest/releases/releases
[the latest release]: https://docs.github.com/en/rest/releases/releases#get-the-latest-release

**Comment by aucampia** [comment]
Can you clarify why?

**Comment by nikitabarskov** [comment]
> Can you clarify why?

I will automate the downloading of checksums file from GH API. So it will have the same workflow as we do for the poetry:

- `make update-terraform-switcher-checksums` will update the checksum file in the repository (it may potentially have a flag for version: `latest` or specific version);
- `make install-terraform-switched` will download the binary and validate checksums;

I agree almost with a majority of what you said in the PR, this issue will just automate the downloading checksums of the file from the repo.

**Comment by aucampia** [comment]
As noted in the PR, as this issue is written it suggests that we change the image to no longer comply with our [guidelines](https://playbook.internal.coop/guidelines/security/supply_chain.html?h=lock#version-locking)

> Lock the versions of your dependencies. When locking the version of a dependency **a checksum for the exact version of the dependency is store in your source code repository and used to reinstall the exact same version.** 

Latest is not an exact version.

**Comment by kvendingoldo** [comment]
btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.
