### ISSUE TITLE
devtools-kubernetes: Make terraform-switcher optional and default to not using it

### ISSUE THREAD

**Issue by aucampia** [coopnorge/engineering-docker-images#94]
With dependabot and locked docker image references the problems with updating Terraform versions in devtools/CI is not as serious as before, as the updates will come in via pull requests which can just not be merged if they break something.

This somewhat reduces the need for terraform-switcher, as most projects can and should keep up to date with the latest Terraform. 

Further we have had a situation where terraform-switcher broke (https://github.com/warrensbox/terraform-switcher/issues/224) - and now basically blocks CI for projects that do not really need it. Basically the less things we depend on the less things can break.

For these reasons I think it may make sense to make terraform-switcher optional, default to not using it, and only enable it if the `WITH_TFSWITCH` environment variable is set to 1.

**Comment by nikitabarskov** [comment]
I am fine with this flag, the default behaviour without tfswitch is okay.

**Comment by AtzeDeVries** [comment]
i agree it. I think it would be nice to then also use the terraform version as tag (and maybe append with short has to rotate other versions). This will give easier insight in which version is used.
